services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - br-net
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - .:/var/www/public
      - /var/www/public/vendor/
      - /var/www/public/node_modules/
      - ./cfg/php.production.ini:/usr/local/etc/php/php.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: regmondb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: regmon123
      STAGE: production

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    networks:
      - br-net
    ports:
      - 8888:80
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root123

  db:
    image: mysql:8.4
    networks:
      - br-net
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: regmondb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: regmon123
      MYSQL_ROOT_PASSWORD: root123

volumes:
  mysql_data:
    driver: local

networks:
  br-net:
    driver: bridge
